* Array vs List: memory effient, expandable easily to N-dimensions, calculation speed, broadcasting operations


### Importing Numpy Library

In [1]:
import numpy as np #alias

#vectors, arrays, matrices, number generation

### Numpy Arrays

In [3]:
#vectors-->> 1D arrays, matrices-->>2D arrays
my_lst = [1,2,3]
my_array = np.array(my_lst)

In [4]:
type(my_lst)

list

In [5]:
type(my_array)

numpy.ndarray

In [6]:
my_array #1 [ after ( means its 1-D

array([1, 2, 3])

In [7]:
my_lst3 = [[1,2,3],[4,5,6],[7,8,9]]
my_lst3

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [9]:
my_mat = np.array(my_lst3)
type(my_mat)

numpy.ndarray

### Built-In methods to create arrays

In [10]:
#arange

np.arange(7)

array([0, 1, 2, 3, 4, 5, 6])

In [11]:
np.arange(3,9)

array([3, 4, 5, 6, 7, 8])

In [12]:
np.arange(3,19,2)

array([ 3,  5,  7,  9, 11, 13, 15, 17])

In [13]:
np.arange(2,4,20)

array([2])

In [14]:
#zeros and ones

np.zeros(3)

array([0., 0., 0.])

In [15]:
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [16]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [21]:
#linspace : return evenly spaced numbers over a specified interval

np.linspace(0,10,21)

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,
        5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. ])

In [20]:
#eye: creates an identity matrix

np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

### Random

In [29]:
#rand : create an array of the given shape and populates it with 
#random samples from a uniform distribution over [0,1)

np.random.rand(3,4)

array([[0.43019941, 0.98245295, 0.43522376, 0.3844637 ],
       [0.08835175, 0.84260063, 0.4471829 , 0.42707825],
       [0.28417214, 0.77548925, 0.65397673, 0.70115318]])

In [30]:
np.random.rand(3)

array([0.79128185, 0.01653138, 0.79637285])

In [32]:
#returns samples from 'standard normal distribution' [sigma = 1]
np.random.randn(5,5)

array([[-0.19819093, -0.15498877,  0.28568915,  1.23129572, -1.65046849],
       [-0.76601998, -0.66880409,  0.11364413,  0.35763512,  0.97517382],
       [-1.45919237,  0.07349689, -0.23330309, -0.1932716 ,  1.48481228],
       [-1.36035616, -1.13837818,  0.08589331, -0.60981423, -0.60972643],
       [-1.23950689,  0.64940509, -1.12918693,  0.22648097, -0.13351206]])

In [38]:
#return random integers from low(inclusive) to high(exclusive)

np.random.randint(0,90)

66

In [57]:
np.random.randint(0,90,38)

array([74, 40, 15, 88, 77, 82,  4, 69, 69, 50, 39, 42,  8, 63, 67, 66,  9,
       88, 41, 46,  9, 13, 35, 79, 10, 89, 65, 75, 21, 20, 31, 46,  8,  5,
       55, 84, 38, 34])

In [54]:
#seed : sets the random state; same random results will be reproduced over and over again irrespective of system, enviornment etc.

np.random.seed(61)
np.random.randint(10,200,6)

array([109,  28, 172,  26, 185,  44])

### Array Attributes and Methods



In [66]:
arr = np.arange(25)
ranarr = np.random.randint(0,40,10)

In [67]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [69]:
arr.shape

(25,)

In [68]:
ranarr

array([34, 19, 10,  5, 34, 38,  3, 34, 15, 15])

In [71]:
#reshape: returns an array with a new shape
arr_55 = arr.reshape(5,5)

In [72]:
arr_55.shape

(5, 5)

In [75]:
arr_1_25 = arr.reshape(1,25)

In [76]:
arr_1_25.shape

(1, 25)

In [80]:
arr_1_25

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [77]:
ARR_25_1 = arr.reshape(25,1)

In [78]:
ARR_25_1.shape

(25, 1)

In [79]:
arr_1_25

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [81]:
ARR_25_1

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [82]:
arr_55

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [83]:
arr_55.dtype

dtype('int64')

In [84]:
arr_float = np.array([1.2,3.4,5.7])

In [85]:
arr_float.dtype

dtype('float64')