In [1]:
import numpy as np

In [3]:
arr = np.arange(0,22, 3)
arr

array([ 0,  3,  6,  9, 12, 15, 18, 21])

In [4]:
arr[2]

6

In [5]:
arr[0:4]

array([0, 3, 6, 9])

### Broadcasting

In [7]:
arr[0:4] = 100

In [8]:
arr

array([100, 100, 100, 100,  12,  15,  18,  21])

In [9]:
arr = np.arange(0,22, 3)

In [10]:
slice_of_arr = arr[0:4]
slice_of_arr

array([0, 3, 6, 9])

In [11]:
slice_of_arr[:] = 99
slice_of_arr

array([99, 99, 99, 99])

In [12]:
arr

array([99, 99, 99, 99, 12, 15, 18, 21])

In [13]:
#data is not copied, slice of array here is just a view of original array

In [14]:
arr_copy = arr.copy()

In [15]:
arr_copy

array([99, 99, 99, 99, 12, 15, 18, 21])

In [16]:
slice_of_arr = arr_copy[0:4]
slice_of_arr[:] = 9999

In [17]:
slice_of_arr

array([9999, 9999, 9999, 9999])

In [18]:
arr

array([99, 99, 99, 99, 12, 15, 18, 21])

### Indexing a 2D array(Matrices)

In [21]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [23]:
#indexing a row
arr_2d[1]

array([20, 25, 30])

In [24]:
arr_2d[2]

array([35, 40, 45])

In [26]:
arr_2d[1][1]

25

In [27]:
arr_2d[2][2]

45

In [28]:
arr_2d[0,2]

15

In [29]:
#slice a 2D matrix
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [31]:
arr_2d[2,1:]

array([40, 45])

In [34]:
arr_sample = np.arange(0,60,3).reshape(4,5)
arr_sample 

array([[ 0,  3,  6,  9, 12],
       [15, 18, 21, 24, 27],
       [30, 33, 36, 39, 42],
       [45, 48, 51, 54, 57]])

In [36]:
#18,21,24
#33,36,39

arr_sample[1:3,1:4]

array([[18, 21, 24],
       [33, 36, 39]])

### Conditional Selection


In [38]:
arr = np.arange(0,52, 3)
arr

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51])

In [39]:
arr > 15

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True])

In [40]:
arr[arr>15]

array([18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51])

In [42]:
arr[arr == 18]

array([18])

In [45]:
arr[arr > np.round(123/11,0)]

array([12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51])

### Numpy Operations

In [46]:
#arithmetic
arr

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51])

In [47]:
arr+arr

array([  0,   6,  12,  18,  24,  30,  36,  42,  48,  54,  60,  66,  72,
        78,  84,  90,  96, 102])

In [48]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [49]:
arr*arr

array([   0,    9,   36,   81,  144,  225,  324,  441,  576,  729,  900,
       1089, 1296, 1521, 1764, 2025, 2304, 2601])

In [50]:
arr/arr

/var/folders/wl/v3x3g82n3b38s3cvwvtr0r7h0000gn/T/ipykernel_2847/1862401812.py:1: RuntimeWarning: invalid value encountered in divide
  arr/arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.])

In [53]:
arr**2

array([   0,    9,   36,   81,  144,  225,  324,  441,  576,  729,  900,
       1089, 1296, 1521, 1764, 2025, 2304, 2601])

In [52]:
1/arr

/var/folders/wl/v3x3g82n3b38s3cvwvtr0r7h0000gn/T/ipykernel_2847/255282349.py:1: RuntimeWarning: divide by zero encountered in divide
  1/arr


array([       inf, 0.33333333, 0.16666667, 0.11111111, 0.08333333,
       0.06666667, 0.05555556, 0.04761905, 0.04166667, 0.03703704,
       0.03333333, 0.03030303, 0.02777778, 0.02564103, 0.02380952,
       0.02222222, 0.02083333, 0.01960784])

### Universal Array Functions

In [54]:
#square root

np.sqrt(arr)

array([0.        , 1.73205081, 2.44948974, 3.        , 3.46410162,
       3.87298335, 4.24264069, 4.58257569, 4.89897949, 5.19615242,
       5.47722558, 5.74456265, 6.        , 6.244998  , 6.4807407 ,
       6.70820393, 6.92820323, 7.14142843])

In [55]:
#exponential
np.exp(arr)

array([1.00000000e+00, 2.00855369e+01, 4.03428793e+02, 8.10308393e+03,
       1.62754791e+05, 3.26901737e+06, 6.56599691e+07, 1.31881573e+09,
       2.64891221e+10, 5.32048241e+11, 1.06864746e+13, 2.14643580e+14,
       4.31123155e+15, 8.65934004e+16, 1.73927494e+18, 3.49342711e+19,
       7.01673591e+20, 1.40934908e+22])

In [56]:
np.sin(arr)

array([ 0.        ,  0.14112001, -0.2794155 ,  0.41211849, -0.53657292,
        0.65028784, -0.75098725,  0.83665564, -0.90557836,  0.95637593,
       -0.98803162,  0.99991186, -0.99177885,  0.96379539, -0.91652155,
        0.85090352, -0.76825466,  0.67022918])

In [57]:
#natural log
np.log(arr)

/var/folders/wl/v3x3g82n3b38s3cvwvtr0r7h0000gn/T/ipykernel_2847/4215628813.py:2: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 1.09861229, 1.79175947, 2.19722458, 2.48490665,
       2.7080502 , 2.89037176, 3.04452244, 3.17805383, 3.29583687,
       3.40119738, 3.49650756, 3.58351894, 3.66356165, 3.73766962,
       3.80666249, 3.87120101, 3.93182563])

In [58]:
np.lcm(12, 20)

60

### Summary Statistics

In [59]:
arr

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51])

In [60]:
arr.sum()

459

In [61]:
arr.mean()

25.5

In [62]:
arr.std()

15.56438241627338

In [63]:
arr.max()

51

In [64]:
arr.min()

0

In [65]:
arr.var()

242.25

#### Axis Logic

* In arrays terms : axis 0 -->> vertical axis (rows)
* axis 1 -->> horizontal axis (columns)

In [66]:
arr_sample 

array([[ 0,  3,  6,  9, 12],
       [15, 18, 21, 24, 27],
       [30, 33, 36, 39, 42],
       [45, 48, 51, 54, 57]])

In [67]:
arr_sample.sum()

570

In [68]:
arr_sample.sum(axis = 0)

array([ 90, 102, 114, 126, 138])

In [69]:
arr_sample.shape

(4, 5)

In [70]:
arr_sample.sum(axis = 1)

array([ 30, 105, 180, 255])

In [72]:
arr_sample.mean(axis = 0)

array([22.5, 25.5, 28.5, 31.5, 34.5])

In [73]:
arr_sample.mean(axis = 1)

array([ 6., 21., 36., 51.])